#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="${BRA:-$HOME}"

ALERT_LOW="${ALERT_LOW:-90%}" # color will turn red under this value (default: 10%)

RES="$(df -h --output=pcent "$DIR" | tail -n 1)"

echo $LABEL $RES
echo $LABEL $RES

if [[ "$RES" > "$ALERT_LOW" ]]; then
    echo "#FF8000" 
else
    echo "#FFFFFF"
fi


exit 0
